package com.chemasmas.uamasesoratemvn.models;
// Generated 4/04/2018 08:58:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Divisiones generated by hbm2java
 */
public class Divisiones  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set ueases = new HashSet(0);

    public Divisiones() {
    }

    public Divisiones(String nombre, Set ueases) {
       this.nombre = nombre;
       this.ueases = ueases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUeases() {
        return this.ueases;
    }
    
    public void setUeases(Set ueases) {
        this.ueases = ueases;
    }




}


