package com.chemasmas.uamasesoratemvn.models;
// Generated 4/04/2018 08:58:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String correo;
     private String telefono;
     private Set profesoresHasUeases = new HashSet(0);

    public Profesores() {
    }

    public Profesores(String nombre, String correo, String telefono, Set profesoresHasUeases) {
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.profesoresHasUeases = profesoresHasUeases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getProfesoresHasUeases() {
        return this.profesoresHasUeases;
    }
    
    public void setProfesoresHasUeases(Set profesoresHasUeases) {
        this.profesoresHasUeases = profesoresHasUeases;
    }




}


