package com.chemasmas.uamasesoratemvn.models;
// Generated 4/04/2018 08:58:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProfesoresHasUeas generated by hbm2java
 */
public class ProfesoresHasUeas  implements java.io.Serializable {


     private ProfesoresHasUeasId id;
     private Profesores profesores;
     private Ueas ueas;
     private String lugar;
     private Date inicio;
     private Date fin;

    public ProfesoresHasUeas() {
    }

	
    public ProfesoresHasUeas(ProfesoresHasUeasId id, Profesores profesores, Ueas ueas) {
        this.id = id;
        this.profesores = profesores;
        this.ueas = ueas;
    }
    public ProfesoresHasUeas(ProfesoresHasUeasId id, Profesores profesores, Ueas ueas, String lugar, Date inicio, Date fin) {
       this.id = id;
       this.profesores = profesores;
       this.ueas = ueas;
       this.lugar = lugar;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public ProfesoresHasUeasId getId() {
        return this.id;
    }
    
    public void setId(ProfesoresHasUeasId id) {
        this.id = id;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public Ueas getUeas() {
        return this.ueas;
    }
    
    public void setUeas(Ueas ueas) {
        this.ueas = ueas;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


