package com.chemasmas.uamasesoratemvn.models;
// Generated 4/04/2018 08:58:21 AM by Hibernate Tools 4.3.1



/**
 * ProfesoresHasUeasId generated by hbm2java
 */
public class ProfesoresHasUeasId  implements java.io.Serializable {


     private int profesor;
     private int uea;

    public ProfesoresHasUeasId() {
    }

    public ProfesoresHasUeasId(int profesor, int uea) {
       this.profesor = profesor;
       this.uea = uea;
    }
   
    public int getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(int profesor) {
        this.profesor = profesor;
    }
    public int getUea() {
        return this.uea;
    }
    
    public void setUea(int uea) {
        this.uea = uea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProfesoresHasUeasId) ) return false;
		 ProfesoresHasUeasId castOther = ( ProfesoresHasUeasId ) other; 
         
		 return (this.getProfesor()==castOther.getProfesor())
 && (this.getUea()==castOther.getUea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProfesor();
         result = 37 * result + this.getUea();
         return result;
   }   


}


